[scenario]
name = "Basic HTTP Test"
description = "Simple HTTP GET test scenario"

[load_profile]
type = "constant"
users = 1
duration = "10s"

[[steps]]
name = "GET Homepage"
protocol = "http"
method = "GET"
url = "https://httpbin.org/get"

[steps.assertions]
status = 200
max_response_time = "2000ms"

[[steps]]
name = "POST Echo"
protocol = "http"
method = "POST"
url = "https://httpbin.org/post"
body = '{"test": "data"}'

[steps.headers]
"Content-Type" = "application/json"

[steps.assertions]
status = 200
